## **계단 함수 구현**

In [2]:
import numpy as np

In [3]:
# 계단 함수 구현
def step_function(x):
    y = x > 0
    return y.astype(y)

In [4]:
x = np.array([-1.0,1.0,2.0])
print(x)
y = x > 0 
print(y)
print(y.astype(np.int))

[-1.  1.  2.]
[False  True  True]
[0 1 1]


## **시그모이드 함수 구현**

In [5]:
def sigmoid_function(x):
    return 1/(1+np.exp(-x))

In [6]:
sigmoid_function(x)

array([0.26894142, 0.73105858, 0.88079708])

## **ReLu 함수 구현**

In [7]:
def relu(x):
    if x > 0:
        return x
    else:
        return 0 

In [8]:
relu(0.1)

0.1

In [9]:
X = np.array([1.0,0.5]) # shape 2,
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]]) # shape (2,3)
B1 = np.array([0.1,0.2,0.3]) # shape 3,

A1 = np.dot(X,W1)+B1
print('A1의 결과값:',A1)
print('X.shape:',X.shape,'W1.shape:',W1.shape,'B1.shape:', B1.shape)

A1의 결과값: [0.3 0.7 1.1]
X.shape: (2,) W1.shape: (2, 3) B1.shape: (3,)


In [10]:
Z1 = sigmoid_function(A1)
print('Z1의 결과값:',Z1)

Z1의 결과값: [0.57444252 0.66818777 0.75026011]


In [11]:
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])

In [12]:
A2 = np.dot(Z1,W2) + B2
print('A2의 결과값:',A2)

A2의 결과값: [0.51615984 1.21402696]


In [13]:
Z2 = sigmoid_function(A2)
print('Z2의 결과값:',Z2)

Z2의 결과값: [0.62624937 0.7710107 ]


In [14]:
def identity_function(x):
    return x

In [15]:
W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])

A3 = np.dot(Z2,W3)+B3
Z3 = identity_function(A3)
print('Z3의 결과값:',Z3)

Z3의 결과값: [0.31682708 0.69627909]


In [16]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]]) 
    network['b3'] = np.array([0.1,0.2])
    
    return network
    
def forward(network,x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    a1 = np.dot(x,W1) + b1
    z1 = sigmoid_function(a1)
    a2 = np.dot(z1,W2) + b2
    z2 = sigmoid_function(a2)
    a3 = np.dot(z2,W3) + b3
    Y = identity_function(a3)
    
    return Y
    

In [17]:
network = init_network()
x = np.array([1.0,0.5])
result = forward(network,x)
print(result)

[0.31682708 0.69627909]


In [18]:
a = np.array([0.3,2.9,4.0])

In [19]:
exp_a = np.exp(a)
print('exp_a:',exp_a)

exp_a: [ 1.34985881 18.17414537 54.59815003]


In [21]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


## **소프트맥스 함수 구현**

In [22]:
y1 = exp_a[0] / sum_exp_a
print(y1)
y2 = exp_a[1] / sum_exp_a
print(y2)
y3 = exp_a[2] / sum_exp_a
print(y3)

0.018211273295547534
0.2451918129350739
0.7365969137693785


In [23]:
def softmax(x):
    exp_a_max = x - np.max(x)
    exp_a = np.exp(exp_a_max)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [24]:
a = np.array([1010,1000,990])
b = softmax(a)
np.sum(b)

1.0

## **MNIST 데이터셋**

In [27]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from dataset.mnist import load_mnist
import matplotlib.pyplot as plt
%matplotlib inline
from PIL import Image # 이미지 표시 모듈
import pickle

In [26]:
(x_train,y_train), (x_test,y_test) = load_mnist(flatten=True,normalize=False)

In [28]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [29]:
# 데이터 시각화
def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()

# 데이터 정보
img = x_train[0]
label = y_train[0]
print(label)

# 데이터 변환
print(img.shape)
img = img.reshape(28,28)
print(img.shape)

img_show(img)

5
(784,)
(28, 28)


In [33]:
def get_data():
    (x_train,y_train), (x_test, y_test) = load_mnist(normalize=True, flatten=True, one_hot_label=False)
    return x_test, y_test

def init_network():
    with open('./sample_weight.pkl','rb') as f: # 가중치 정보를 f에 저장
        network = pickle.load(f)
    return network

def predict(network, x):
    W1, W2 ,W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x,W1) + b1
    z1 = sigmoid_function(a1)
    a2 = np.dot(z1,W2) + b2
    z2 = sigmoid_function(a2)
    a3 = np.dot(z2,W3) + b3
    y = softmax(a3)
    
    return y

In [42]:
x_test, y_test = get_data() # 데이터 불러오기
network = init_network() # 가중치값 할당

accuracy_cnt = 0 # 정확도 변수 초기화

for i in range(len(x_test)):
    y = predict(network, x_test[i])
    p = np.argmax(y)
    if p == y_test[i]:
        accuracy_cnt += 1
print('정확도:',float(accuracy_cnt/len(x_test)))

정확도: 0.9352


In [50]:
x_test, y_test = get_data()
network = init_network()

batch_size = 100
accuracy_cnt = 0

for i in range(0, len(x_test), batch_size):
    x_batch = x_test[i:i+batch_size]
    y_batch = predict(network, x_batch)
    p = np.argmax(y_batch, axis=1)
    accuracy_cnt += np.sum(p==y_test[i:i+batch_size])
    
print('정확도:',float(accuracy_cnt/len(x_test)))

정확도: 0.9352
